name: Build

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions: write-all

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '10.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet publish -c Release --no-restore

            - name: Create Directories
              run: |
                mkdir -p plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}

            - name: Move Plugin
              run: |
                mv ./build/net10.0/${{ github.event.repository.name }}.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}

            - name: Copy Logger
              run: |
                cp ./build/net10.0/RLogger.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}

            - name: Copy Shared
              run: |
                cp ./build/net10.0/${{ github.event.repository.name }}.Shared.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}

            - name: Create Module Directories
              run: |
                mkdir -p plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Aliases/resources/exports
                mkdir -p plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Messages/resources/exports
                mkdir -p plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Played/resources/exports

            - name: Move Module Plugins
              run: |
                mv ./build/net10.0/${{ github.event.repository.name }}.Aliases.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Aliases
                mv ./build/net10.0/${{ github.event.repository.name }}.Messages.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Messages
                mv ./build/net10.0/${{ github.event.repository.name }}.Played.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Played

            - name: Copy Module Loggers
              run: |
                cp ./build/net10.0/RLogger.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Aliases
                cp ./build/net10.0/RLogger.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Messages
                cp ./build/net10.0/RLogger.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Played
                
            - name: Copy Module Shared
              run: |
                cp ./build/net10.0/${{ github.event.repository.name }}.Shared.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Aliases/resources/exports
                cp ./build/net10.0/${{ github.event.repository.name }}.Shared.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Messages/resources/exports
                cp ./build/net10.0/${{ github.event.repository.name }}.Shared.dll ./plugin/addons/swiftlys2/plugins/${{ github.event.repository.name }}.Played/resources/exports

            - name: Zip
              run: |
                cd ./plugin
                zip -r ${{ github.event.repository.name }}-${{ github.sha }}.zip .

            - name: Publish
              uses: actions/upload-artifact@v4
              with:
                name: ${{ github.event.repository.name }}-${{ github.sha }}
                path: ./plugin

            - name: Extract version
              id: extract_version
              run: |
                version=$(grep -oP 'Version = "\K(.*)(?=")' ./src/${{ github.event.repository.name }}.cs | head -1)
                echo "version=$version" >> $GITHUB_OUTPUT

            - name: Create Tag
              run: |
                git config --global user.email "actions@github.com"
                git config --global user.name "GitHub Actions"
                git tag ${{ steps.extract_version.outputs.version }}
                git push origin ${{ steps.extract_version.outputs.version }}

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.extract_version.outputs.version }}
                  release_name: ${{ steps.extract_version.outputs.version }}
                  body: |
                      This is an automated release.
                  draft: false
                  prerelease: false

            - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./plugin/${{ github.event.repository.name }}-${{ github.sha }}.zip
                  asset_name: ${{ github.event.repository.name }}.zip
                  asset_content_type: application/zip

            